apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: dev-container-root
  namespace: default
  description: Point d'entrée du Catalog CMA CGM — dev container
spec:
  targets:
    - ./mounted/templates/catalog.yaml
