apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: dev-container-templates
  namespace: default
  description: Templates générés par le dev container CMA CGM
spec:
  targets:
    - https://github.com/ikto-cma-cgm/dev-container/raw/liquibase-springboot-composition/output/templates/springboot-service-template/template.yaml
    - https://github.com/ikto-cma-cgm/dev-container/raw/liquibase-springboot-composition/output/templates/liquibase-service-template/template.yaml
    - https://github.com/ikto-cma-cgm/dev-container/raw/liquibase-springboot-composition/output/templates/springboot-liquibase-composition-template/template.yaml
