openapi: 3.0.1
info:
  x-api-type: system
  x-hopex: 
    - componentCode: IS06258
  title: Container Tracking service API - To track container moves
  description: >-
    <P>CMA CGM API for managing and tracking equipment related events and container movements.</P> 
  version: 1.5.1
servers:
- url: /logistic/tracking/container/system/v1
tags:
- name: Container Tracking
  description: Containers event operations
- name: Container Moves
  description: Container Movement operations

paths:
  /containers/moves:
    post:
      tags:
        - Container Moves
      summary: Validate and Insert Container Moves
      description: Method that will call a procedure on LARA side, P_Main. Procedure will validate the input data and insert the move if validation is OK.
      operationId: createContainerMoves
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ContainerMove'
      responses:
        '201':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ContainerMoveResponse"
        '400':
          description: >- 
            'Fault Description: Reason - 400 Bad request'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fault'
        '500':
          description: >-
            'Fault Description: Reason -  500 Internal server error'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fault'
      security: 
        - oAuth2:
          - containermove:write:be
          - containermove:write:fe

  '/containers/trackingevents':
    get:
      tags:
      - Container Tracking
      operationId: searchContainerTrackingEvent
      summary: Find container tracking events.
      description: 
        Returns all container tracking events filtered by the queryParameters.
      parameters:
      - name: bookingReference
        in: query
        description: Booking reference related to the container. When filled, only container tracking moves related to that booking reference are returned.
        schema:
          type: string
      - name: bolNumber
        in: query
        description: BL number related to the container. When filled, only container tracking moves related to that BL reference are returned.
        schema:
          type: string
      - name: containerNumber
        in: query
        description: 
          Container Number. When filled, only specific moves related to a single container are returned.
        schema:
          type: string
      - name: startDate
        in: query
        description: Start Events Date
        schema:
          type: string
          format: date
      - name: endDate
        in: query
        description: End Evernts Date
        schema:
          type: string
          format: date
      - name: containerStatus
        in: query
        description: Container status
        schema:
          type: string
      - name: containerCodeType
        in: query
        description: Container code type
        schema:
          type: array
          items: 
            type: string
            default: 'CCST'
        example: ["CNST", "CCST"]
      - name: meaEvents
        in: query
        description: Boolean parameter that will define if the MEA movements of the container need to be included in the response. Depending on this parameter different queries will run.
        schema:
          type: boolean
          default: false  
      - name: bookingInheritance
        in: query
        description: Boolean parameter that will define if all parent-child relations of the booking need to be included in the response. This flag have the efect only in case that meaEvents flag is set to true. Depending on these to flags different query will be run.
        schema:
          type: boolean
          default: false
      - in: header
        name: range
        schema:
          type: string
          default: 0-49
        required: false
        description: Pagination parameter. default 0-49. Maximum rows to return 50

      responses:
        "200":
          description: Successful operation
          headers:
            Content-Range:
              description: 'Returned range.'
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ContainerTracking'
        '206':
          description: 'Successful operation but partial content'
          headers:
            Content-Range:
              description: 'Returned range.'
              schema:
                type: string
          content:
            application/json:
              schema:
                type: array
                items:
                   $ref: '#/components/schemas/ContainerTracking'
        "400":
          description: hereunder fault datatype description<br> Reason - 400 Bad Request<b>Description - Invalid request parameter(s)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fault'
        "404":
          description: hereunder fault datatype description<br> Reason - 404 Resource Not Found<br>Description - Requested resource could not be found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fault'
        "405":
          description: hereunder fault datatype description<br> Reason - 405 Method not allowed<br> Description - Resource does not support this method.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fault'
        "416":
          description: hereunder fault datatype description<br> Reason - 416 Range not satisfiable<br> Description - Requested range cannot be served.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fault'
        "500":
          description: hereunder fault datatype description<br> Reason - 500 Internal Server Error<br>  Description - An unexepected error occurred while processing the request.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Fault'

      security:
        - oAuth2:
            - 'containertracking:read:be'
            - 'containertracking:read:fe'

components:
  schemas: 
    ContainerTracking:
      type: object
      required:
        - status
        - statusDate
        - statusTime
        - containerNumber
      properties:
        bolNumber:
          type: string
          description: bill of lading number
          example: 'LHV2938678'
        jobReference:
          type: string
          description: booking reference
          example: 'SGN1525922'
        containerNumber:
          type: string
          description: Container number
          example: 'CMAU0209762'
        status:
          description: container status
          type: string
          example: 'TOF'
        statusDate:
          type: string
          format: date
          description: Container status date
          example: "2023-11-10"
        statusTime:
          type: number
          description: Container status time
          example: 1025
        statusDateTime:
          type: string
          description: date-time of the status update
          format: date-time
          example: "2023-11-10T15:00:00.00Z"
        statusOrder:
          description: movement display order
          type: string
          example: "2"
        description:
          type: string
          description: Description of container movement
          example: Gate in at port terminal
        moveDateTime:
          type: string
          description: The date time of the container movement
          format: date-time
          example: "2024-12-11T15:00:00.00Z"
        reportedOn:
          type: string
          description: The date and time when container movement is inserted in LARA
          format: date-time
          example: "2024-12-11T15:00:00.00Z"
        loadEmptyFlag:
          description: load empty flag
          type: string
          example: 'L'
        currentLocation:
          $ref: '#/components/schemas/Location'
        transport:
          $ref: '#/components/schemas/Transport'
        bookingInheritance:
          $ref: '#/components/schemas/BookingInheritance'
    BookingInheritance:
      type: object
      properties:
        mainBookingReference:
          type: string
          description: Main booking reference
          example: "AYN1082210"
        level1:
          type: array
          items:
            $ref: '#/components/schemas/BookingRelationshipLevel1'
    BookingRelationshipLevel1:
      type: object
      properties:
        bookingReference:
          type: string
          description: Child booking reference
          example: "AYN1082210B"
        childType:
          type: string
          description: Type of the chiled booking reference depending on the relation of the main booking. It can be Split - S, Merge - M, PartLoad - P 
          example: "S" 
        level2:
          type: array
          items:
            $ref: '#/components/schemas/BookingRelationshipLevel2'
    BookingRelationshipLevel2:
      type: object
      properties:
        bookingReference:
          type: string
          description: Child booking reference
          example: "AYN1082210B"
        childType:
          type: string
          description: Type of the chiled booking reference depending on the relation of the main booking. It can be Split - S, Merge - M, PartLoad - P 
          example: "S" 
        level3:
          type: array
          items:
            $ref: '#/components/schemas/BookingRelationshipLevel3'
    BookingRelationshipLevel3:
      type: object
      properties:
        bookingReference:
          type: string
          description: Child booking reference
          example: "AYN1082210B"
        childType:
          type: string
          description: Type of the chiled booking reference depending on the relation of the main booking. It can be Split - S, Merge - M, PartLoad - P 
          example: "S" 
        level4:
          type: array
          items:
            $ref: '#/components/schemas/BookingRelationshipLevel4'
    BookingRelationshipLevel4:
      type: object
      properties:
        bookingReference:
          type: string
          description: Child booking reference
          example: "AYN1082210B"
        childType:
          type: string
          description: Type of the chiled booking reference depending on the relation of the main booking. It can be Split - S, Merge - M, PartLoad - P 
          example: "S" 
        level5:
          type: array
          items:
            $ref: '#/components/schemas/BookingRelationshipLevel5'
    BookingRelationshipLevel5:
      type: object
      properties:
        bookingReference:
          type: string
          description: Child booking reference
          example: "AYN1082210B"
        childType:
          type: string
          description: Type of the chiled booking reference depending on the relation of the main booking. It can be Split - S, Merge - M, PartLoad - P 
          example: "S" 
    Transport:
      type: object
      required:
        - placeOfOrigin
        - placeOfDestination
      properties:
        placeOfOrigin:
          type: string
          description: Origin pool, LARA location code
          example: 'LSG'
        placeOfDestination:
          type: string
          description: Destination pool, LARA location code
          example: 'RPS'
        actualPortOfLoading:
          type: string
          description: Actual port of loading code
          example: 'FRMRS'
        actualPortOfDischarge:
          type: string
          description: Actual port of Discharge code
          example: 'FRMRS'
        finalPortOfDischarge:
          type: string
          description: Port of Discharge Code
          example: 'FRMRS'
        transportMode:
          type: string
          description: Mode of Transport
          example: 'Ship'
        voyageReference:
          type: string
          description: current voyage reference
          example: '0LB7YW1MA'
        shippingCompany:
          type: string
          description: properties for shipcompCode
          example: '0001'
          
    Location:
      type: object
      properties:
        name:
          type: string
          description: Location name
          example: 'LONDON'
        pointCode:
          type: string
          description: Location point code
          example: 'LOND'   
        poolCode:
          type: string
          description: Pool location code
          example: 'CTAODQCT'

    ContainerMove:
      type: object
      properties:
        poolLocationCodeFrom:
          type: string
          description: Pool code - from location
          example: GRPIRTFAS
        poolLocationCodeTo:
          type: string
          description: Pool code - to location
          example: GRPIRTFAS
        containerStatus:
          description: Conainer status
          type: string
          example: MEI 
        containerStatusDate:
          description: Date of the container status
          type: string
          format: date
          example: '2022-04-05'
        containerStatusTime:
          description: Time of the container status defined as integer
          type: integer
          format: date-time
          example: 2213
        modeOfTransport:
          description: Selected mode of transport for example RD -> Road or RL -> Rail
          type: string
          example: RD
        intelligentNumber:
          type: string
          description: Intelligent number of container equivalent to shipping order number
          example: "3356789"
        bookingReference:
          type: string
          description: Booking reference information
          example: DXB0577908
        shippingCompany:
          type: string
          description: shipping companies codes are 0001, 0002... provided by CMA CGM referential
          example: '0001'
        billOfLadingNumber:
          type: string
          description: LARA BL reference
          example: TPEBA1222800
        releaseReference:
          maxLength: 450
          type: string
          description: Unique release reference
          example: "REL-NUM-456"
        voyageReference:
          type: string
          description: Voyage unique reference
          example: 0JC46N1MA
        vesselCode:
          description: Unique Vessel code
          type: string
          example: 'CGJRS'
        vesselServiceId:
          type: integer
          description: Identifier for the vessel's service.
          example: 6889
        saleReference:
          type: string
          description: Unique sale reference
          example: SAL25/0011
        portOfOrigin:
          description: Port code for the starting point for shipment
          type: string
          example: "FRLEH"
        portOfLoading:
          description: Point of container loading
          type: string
          example: "FRLEH"
        pointOfDischarge:
          description: Point of continaer discharge
          type: string
          example: "CNSHA"
        finalPod:
          description: final port of discharge
          type: string
          example: "CNSHA"
        finalDestination:
          description: final point of destination
          type: string
          example: "CNSHA"
        remarks:
          description: Custom Human-readable additional comments
          example: SCRAP SOLD TO BLUE STAR RECYCLING Travis Evans <travisevans2011@icloud.com> 
          type: string
        containerNumber:
          description: Unique container identifier
          type: string
          example: "ECMU1234567"

    ContainerMoveResponse:
      type: object
      properties:
        success:
          type: boolean
          description: Define if the insert of the container move was successfull or not.
          example: true
        message:
          type: string
          description: Additional Human-readable message. For success cases, value will be 'Data received successfully'. For failure cases, 'Error occurred'  followed by error message. This could be technical error or validation error.
          example: Data received successfully

    Fault:
      required:
      - reason
      type: object
      properties:
        reason:
          type: string
          description: HTTP error or Free text such as  Database Not Available , Invalid
            Credential, Mandatory, Invalid Format,  Invalid Length, Forbidden Value,
            Invalid Data,...
          example: "400 Bad Request"
        code:
          type: string
          description: Error Id,  Server Application error ID, Oracle error Id, ....
          example: "BP_ERR"
        description:
          type: string
          description: Human-readable error description including Data and Value 
          example: "Unrecognized field"

  securitySchemes:
    oAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://auth.cma-cgm.com/as/token.oauth2'
          scopes:
            'containertracking:read:be' : read access for back end
            'containertracking:read:fe' : read access for front end
            'containermove:write:be' : write access for back end
            'containermove:write:fe' : write access for front end
