{% if values.includeDocker %}version: '3.8'

services:
  ${{ values.projectName }}:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${{ values.projectName }}
    environment:
      - CHATBOT_URL=${{ values.chatbotUrl }}
      - NOTIFICATION_TITLE=${{ values.notificationTitle }}
      - NOTIFICATION_MESSAGE=${{ values.notificationMessage }}
      - NOTIFICATION_TYPE=${{ values.notificationType }}
    restart: on-failure
    networks:
      - notification-network

networks:
  notification-network:
    driver: bridge
{% endif %}