pipeline {
    agent any

    environment {
        JAVA_VERSION = '${JAVA_VERSION}'
        APP_NAME = '${APP_NAME}'
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }

        stage('Test') {
            when {
                expression { return ${RUN_TESTS} }
            }
            steps {
                sh 'mvn test'
            }
        }
    }
}
