<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>${{values.group_id}}</groupId>
	<artifactId>${{values.artifact_id}}</artifactId>
	<version>1.0.0</version>
	<packaging>jar</packaging>

	<name>${{values.artifact_id}}</name>
	<description>${{values.description}}</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>${{values.spring_boot_version}}</version>
		<relativePath /> <!-- lookup parent from repository -->
	</parent>
	
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java.version>${{values.java_version}}</java.version>
		<workflow-platform-bom.version>2.0.0</workflow-platform-bom.version>
		{% if values.cloud_file_storage_client -%}<cloud-file-storage-client.version>3.2.0</cloud-file-storage-client.version>{%- endif %}
		{% if values.notification_client -%}<notification-client.version>2.2.0</notification-client.version>{%- endif %}
		{% if values.technical_message_publisher -%}<technical-message-publisher.version>5.3.0</technical-message-publisher.version>{%- endif %}
		{% if values.business_event_publisher -%}<business-event-publisher.version>4.2.1</business-event-publisher.version>{%- endif %}
	</properties>
<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>io.camunda</groupId>
			<artifactId>camunda-spring-boot-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-kubernetes-client-config</artifactId>
		</dependency>
		<!-- Open Tracing -->
		<dependency>
			<groupId>io.opentracing.contrib</groupId>
			<artifactId>opentracing-spring-cloud-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>io.opentracing.contrib</groupId>
			<artifactId>opentracing-spring-jaeger-cloud-starter</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
		<dependency>
			<groupId>com.cma.core</groupId>
			<artifactId>oauth2-resource</artifactId>
		</dependency>
		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-junit-jupiter</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>com.cma.it.development.bpm</groupId>
			<artifactId>workflow-platform-tests-extension</artifactId>
			<scope>test</scope>
		</dependency>		
		
		<!-- Add on -->
		 <!-- Micrometer Cloudwatch will be a flavor depending on Dynatrace or Cloudwatch chosen-->
		<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-registry-cloudwatch2</artifactId>
		</dependency>
		<dependency>
			<groupId>net.logstash.logback</groupId>
			<artifactId>logstash-logback-encoder</artifactId>
		</dependency>
		<!-- End add on cloudwatch -->

		{% if values.open_feign -%}
		<!--Open Feign-->
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-openfeign-core</artifactId>
		</dependency>

		<!-- Circuit Breaker -->
		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-circuitbreaker-resilience4j</artifactId>
		</dependency>
		{%- endif %}

		{% if values.cloud_file_storage_client -%}
		<!--Cloud Storage-->
        <dependency>
            <groupId>com.cma.core</groupId>
            <artifactId>cloud-file-storage-client</artifactId>
            <version>${cloud-file-storage-client.version}</version>
        </dependency>
		{%- endif %}

		{% if values.notification_client -%}
		<!--Notification-->
        <dependency>
            <groupId>com.cma.core</groupId>
            <artifactId>notification-client</artifactId>
            <version>${notification-client.version}</version>
        </dependency>
		{%- endif %}

		{% if values.technical_message_publisher -%}
		<!--Technical Message Publisher-->
        <dependency>
            <groupId>com.cma.core</groupId>
            <artifactId>technical-message-publisher</artifactId>
            <version>${technical-message-publisher.version}</version>
        </dependency>
		{%- endif %}

		{% if values.business_event_publisher -%}
		<!--Business Event Publisher-->
        <dependency>
            <groupId>com.cma.core</groupId>
            <artifactId>business-event-publisher</artifactId>
            <version>${business-event-publisher.version}</version>
        </dependency>
		{%- endif %}

		{% if values.sqs_flavor -%}
		<dependency>
			<groupId>com.cma.core</groupId>
			<artifactId>technical-message-consumer</artifactId>
		</dependency>
		{%- endif %}
	</dependencies>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>com.cma.it.development.bpm</groupId>
				<artifactId>workflow-platform-bom</artifactId>
				<version>${workflow-platform-bom.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>${java.version}</source>
					<target>${java.version}</target>
					<annotationProcessorPaths>
						<path>
							<groupId>org.projectlombok</groupId>
							<artifactId>lombok</artifactId>
						</path>
					</annotationProcessorPaths>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<pluginRepositories>
		<pluginRepository>
			<id>nexus-oss</id>
			<layout>default</layout>
			<url>https://integration.shared-services-prd.aws.cld.cma-cgm.com/nexus/repository/CMA-CGM</url>
		</pluginRepository>
	</pluginRepositories>

	<repositories>
		<repository>
			<id>nexus-oss</id>
			<layout>default</layout>
			<url>https://integration.shared-services-prd.aws.cld.cma-cgm.com/nexus/repository/CMA-CGM</url>
		</repository>
		<repository>
			<id>nexus-oss-releases</id>
			<layout>default</layout>
			<url>https://integration.shared-services-prd.aws.cld.cma-cgm.com/nexus/repository/maven-group/</url>
		</repository>
		<repository>
			<id>nexus-oss-snapshots</id>
			<layout>default</layout>
			<url>https://integration.shared-services-prd.aws.cld.cma-cgm.com/nexus/repository/maven-snapshots</url>
		</repository>
	</repositories>

	<distributionManagement>
		<repository>
			<id>nexus-oss</id>
			<url>https://integration.shared-services-prd.aws.cld.cma-cgm.com/nexus/repository/maven-group/</url>
		</repository>
		<snapshotRepository>
			<id>nexus-oss</id>
			<url>https://integration.shared-services-prd.aws.cld.cma-cgm.com/nexus/repository/maven-snapshots/</url>
		</snapshotRepository>
	</distributionManagement>
</project>
